---
- name: Install Nginx
  hosts: all
  become: yes
  vars:
    ansible_ssh_user: sagarika
    ansible_ssh_private_key_file: /var/lib/jenkins/id_rsa
 
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
 
    - name: Install Nginx
      apt:
        name: nginx
        state: present
